### ISSUE TITLE
filebeat addon doest not show up in hassio after adding repository

### ISSUE THREAD

**Issue by johnhoogeveen** [maretodoric/hassio-filebeat#1]
Hi,

Can it be that the file repository.yaml needs to be renamed to repository.json
After adding the repo to home assistant it does not show up as installable addon.
When checking other addon's I always see that it is a json file and not a yaml.

**Comment by maretodoric** [comment]
Hello there,

You might need to refresh the page for addon to become visible. Try refreshing using CTRL+F5.

If still doesn't work, try visiting [this](https://my.home-assistant.io/redirect/supervisor_addon/?addon=5a615ef2_filebeat&repository_url=https://github.com/maretodoric/hassio-filebeat) URL. There, add link to your home assistant instance if you haven't before and it should redirect you automatically to addon page where you can install addon.

**Comment by johnhoogeveen** [comment]
Hello,

Really strange, I tried several things but none worked, switching from brave to safari and adding the addon it immediately showed up
